### ISSUE TITLE
Path contains invalid characters

### ISSUE THREAD

**Issue by msskaa12** [kennethkn/patreon-scraper-puppeteer#1]
Thanks you for this awesome project. 
after run " npm run setup" in first powershell window , chrome browser was  launched ,and login patreon successfully ,
then I open second powershell window ,run "npm strart" .  a new chrome  program was launched (with a "Test" text  on the icon) , and a empty page was loading , I got error in  powershell window， how to fix it ?

PS D:\Projects\patreon-scraper-puppeteer> npm start

> patreon-scraper-puppeteer@1.0.0 start
> ts-node src/index.ts

Error: Path contains invalid characters: D:\Projects\patreon-scraper-puppeteer\dist\hkstockinvestment\2024-10-14T03:19:48.663Z
    at checkPath (D:\Projects\patreon-scraper-puppeteer\node_modules\fs-extra\lib\mkdirs\utils.js:16:21)
    at Object.module.exports.makeDir (D:\Projects\patreon-scraper-puppeteer\node_modules\fs-extra\lib\mkdirs\make-dir.js:12:3)
    at Object.<anonymous> (D:\Projects\patreon-scraper-puppeteer\node_modules\universalify\index.js:18:45)
    at D:\Projects\patreon-scraper-puppeteer\src\index.ts:60:14 {
  code: 'EINVAL'
}

**Comment by dutchcube** [comment]
Same, got the error path contains invalid characters. 

`patreon-scraper-puppeteer-master\node_modules\fs-extra\lib\mkdirs\utils.js:16:21)`
`patreon-scraper-puppeteer-master\node_modules\fs-extra\lib\mkdirs\utils.js:16:21)`
`patreon-scraper-puppeteer-master\node_modules\fs-extra\lib\mkdirs\make-dir.js:12:3)`
`patreon-scraper-puppeteer-master\node_modules\universalify\index.js:18:45)`
`patreon-scraper-puppeteer-master\src\index.ts:60:14 {`
